project:
  type: website
  output-dir: docs

website:
  title: "uskovgs.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/uskovgs
      
format:
  html:
    theme: flatly
    css: styles.css



