project:
  type: website
  output-dir: docs

website:
  title: "Posts"
  navbar:
    right:
      - icon: github
        href: https://github.com/uskovgs
      - icon: envelope
        href: mailto:uskov.russia@gmail.com
        
        
      
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css



